### ISSUE TITLE
Cannot make new colony with mod enabled.

### ISSUE THREAD

**Issue by Cuber192** [keyz182/AvoidDarkness#2]
[avoid darkness.txt](https://github.com/user-attachments/files/16339325/avoid.darkness.txt)
![new world creation](https://github.com/user-attachments/assets/4758f698-1498-4d83-ad47-56b27c5cfd5f)

Your mod was one of the mods I added today to my game and after I did I could not make new maps.  After looking at the steam page it looked like someone else had the same issue and you asked them to post logs here not sure if I grabbed the right file.  I can still create a map then add the mod after and i don't seem to have any issues.  Also I am using a mis-mash of mods from various youtuber/streamer most of which come from Mr Samuel Streamer, which is how I found your mod.

**Comment by keyz182** [comment]
Fixed, will be published within 5 minutes of this comment.

**Comment by keyz182** [comment]
And thanks for the report!
